library 'cb-days@master'
def testPodYaml = libraryResource 'podtemplates/python/python-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('Python Test and Build')
  {
    stage('Python Tests') {
      agent {
        kubernetes {
          label 'python'
          yaml testPodYaml
       }
      }
      steps {
            checkout scm           
            container('python3') {
              sh '''
                 pipenv install --system
                 '''
            }
      } 
    }
  }
}

